apiVersion: v1
kind: Service
metadata:
  name: llm-service
  labels:
    app: llm-service
spec:
  type: NodePort
  selector:
    app: llm-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
